# Generated by Django 5.2.8 on 2026-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.TextField()),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://neon-factory.com/cdn/shop/products/eat-512-Culinary_-eat_-food_-holiday_-tourism_-travel_-vacation_e99d9a61-53f7-4f9c-95fc-c974cccc1445_1200x1200.png?v=1575239933', max_length=500)),
            ],
        ),
    ]
