# Generated by Django 5.2.8 on 2026-04-11 02:20

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
